In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score
from sklearn import preprocessing
mm_scaler = preprocessing.MinMaxScaler()

# FIRST ATTEMPT (MLP CLASSIFIER)

In [3]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [5]:
#is_long = train_df['AGE']>=20 & train_df['AGE']<30
#train_df[train_df['AGE']>=20 & train_df['AGE']<30]
#is_long = [20,21,22,23,24,25,26,27,28,29]
#boole=train_df['AGE'].isin(is_long)
# train_df[train_df['AGE']==21&train_df['AGE']==20]

In [4]:
train_df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default_payment_next_month'],
      dtype='object')

In [161]:
test_df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object')

In [162]:
#viz = train_df[['LIMIT_BAL','PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6','BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4']]
#viz.hist()
#plt.show()

In [163]:
train_df[train_df['PAY_0'] ==-2]=-1
train_df[train_df['PAY_2'] ==-2]=-1
train_df[train_df['PAY_3'] ==-2]=-1
train_df[train_df['PAY_4'] ==-2]=-1
train_df[train_df['PAY_5'] ==-2]=-1
train_df[train_df['PAY_6'] ==-2]=-1
train_df[train_df['LIMIT_BAL'] ==-1]=0

In [166]:
X1.columns

Index(['LIMIT_BAL', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6',
       'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5',
       'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5',
       'PAY_AMT6', 'default_payment_next_month'],
      dtype='object')

In [165]:
X1 = train_df
X1.drop(['ID', 'EDUCATION', 'MARRIAGE','SEX','AGE'], axis = 1, inplace = True)
#X1.drop(['ID'], axis = 1, inplace = True)

In [126]:
X = X1.iloc[:,0:19]
y = X1.iloc[:,20]
X = mm_scaler.fit_transform(X)
#y = mm_scaler.fit_transform(y)

C:\Users\APOORV\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [127]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=0)

In [128]:
logisticRegr = LogisticRegression()
logisticRegr.fit(X_train, y_train)

C:\Users\APOORV\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [129]:
y_pred = logisticRegr.predict(X_test)
y_predtrain = logisticRegr.predict(X_train)
r2 = r2_score(y_test,y_pred)
r2_train = r2_score(y_train, y_predtrain)

In [130]:
r2

-0.02019843420093803

In [131]:
new_series = pd.Series(y_predtrain)

In [132]:
new_series.value_counts()

0    15540
1     1260
dtype: int64

In [133]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(16,16,16), activation='relu', solver='adam', max_iter=70000,n_layers_=15)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [134]:
new_series = pd.Series(predict_train)

In [135]:
new_series.value_counts()

0    15039
1     1761
dtype: int64

In [136]:
r2 = r2_score(y_test,y_pred)
r2_train = r2_score(y_train, y_predtrain)

In [137]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[13269   525]
 [ 1770  1236]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92     13794
           1       0.70      0.41      0.52      3006

   micro avg       0.86      0.86      0.86     16800
   macro avg       0.79      0.69      0.72     16800
weighted avg       0.85      0.86      0.85     16800

In [138]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[3289  148]
 [ 451  312]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      3437
           1       0.68      0.41      0.51       763

   micro avg       0.86      0.86      0.86      4200
   macro avg       0.78      0.68      0.71      4200
weighted avg       0.84      0.86      0.84      4200

In [139]:
test_df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,10178,60000,2,2,1,30,0,0,0,0,...,38117,38874,38667,39544,1628,1618,1375,1403,1520,1205
1,5304,200000,2,1,2,29,0,0,0,0,...,76593,93988,50292,10510,4160,14593,20150,0,5739,12050
2,5187,230000,1,1,2,39,0,0,0,0,...,20650,0,0,0,2500,2000,0,0,0,0
3,14495,150000,1,1,2,40,0,0,0,0,...,145978,139791,142745,146872,5800,5245,5200,5200,6500,7200
4,20444,140000,1,2,2,27,0,0,0,0,...,76230,77954,78953,81848,10000,10000,3393,3260,5000,3000
5,17667,210000,2,2,2,41,0,0,0,0,...,99865,77754,49529,30683,9000,4000,3018,2000,3000,3000
6,21211,50000,1,2,2,38,0,0,0,0,...,17266,18253,18618,37495,1266,1298,1285,650,825,1582
7,7178,500000,1,2,1,61,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
8,20783,300000,1,1,1,33,0,0,0,0,...,22396,21055,14714,7323,1514,1216,3127,3046,2011,142
9,24033,50000,1,2,2,25,0,0,2,2,...,43032,47242,46212,45205,14200,2100,5215,0,0,0
10,754,500000,2,2,2,43,-1,0,0,0,...,39032,29092,22725,11590,4006,2383,1126,782,596,1572
11,23732,30000,2,2,2,53,-1,-1,0,0,...,16863,7380,8580,10000,15700,2000,2000,1200,2200,0
12,6072,230000,2,2,1,41,0,0,0,0,...,172056,172615,174555,177010,8000,7500,6500,6500,7000,7068
13,17662,290000,2,2,1,49,-2,-2,-1,2,...,11764,11186,6863,6179,0,12000,0,0,0,0
14,5541,20000,2,1,2,23,0,0,0,2,...,17750,17175,18716,18782,1300,2180,0,1818,1000,680
15,22697,80000,2,2,2,36,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
16,29905,60000,1,3,2,30,0,0,0,0,...,54126,58732,59306,59728,2600,4553,5800,2000,1000,1462
17,6695,50000,1,2,2,24,0,0,0,0,...,8741,8911,8943,9140,1290,1294,464,324,345,500
18,12664,10000,1,3,2,28,2,0,0,-1,...,0,1170,9956,9992,1000,1600,1170,9956,282,91
19,15392,300000,2,2,2,42,0,0,0,0,...,108659,110781,107833,104466,5400,5800,6000,7000,5000,5000
20,309,30000,1,3,1,55,2,2,2,3,...,11339,12841,13836,14514,1200,1200,2000,1500,1500,1500
21,16129,200000,2,2,2,32,0,0,0,0,...,13683,-3942,123250,125926,1500,1000,0,128000,4600,5000
22,6324,100000,2,2,2,30,0,0,0,0,...,56058,51573,47665,43756,2801,2300,1613,1594,1654,1222
23,23673,130000,2,2,3,48,-1,-1,-1,2,...,109,109,109,0,0,109,0,0,0,0
24,28889,50000,2,3,2,46,0,0,0,0,...,8770,7251,15948,8838,2500,2127,1500,1000,1000,1000
25,17687,120000,2,2,1,34,0,0,0,0,...,114061,116067,116294,118759,4400,4137,4400,4320,4500,4600
26,27129,360000,1,1,2,34,0,0,0,0,...,366591,331833,288709,290583,15000,15502,13801,9852,10224,10010
27,8487,200000,2,2,2,26,-2,-2,-2,-2,...,2321,327194,6680,3963,1468,2321,163597,6680,3963,2514
28,10304,210000,2,1,1,51,-1,-1,-2,-2,...,0,0,0,0,0,0,0,0,0,0
29,14991,160000,1,3,2,27,1,2,-1,0,...,34073,15676,99436,90927,0,142848,1800,90000,3300,3400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8970,15036,200000,1,1,1,38,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
8971,27479,150000,1,3,2,51,-1,-1,-1,-1,...,2651,2465,4108,4703,3146,2659,2472,4116,4703,4708
8972,29685,280000,1,1,2,32,-2,-2,-2,-2,...,3735,13956,5911,1356,1355,3754,14025,12820,1362,5274
8973,4911,60000,2,1,2,34,2,-1,-1,0,...,823,683,240,998,240,823,0,240,998,223
8974,19213,90000,2,2,1,31,2,2,0,0,...,89779,89214,88847,88724,3500,4400,5013,4000,4000,4000
8975,508,180000,2,2,2,28,0,0,0,0,...,36696,35813,37893,34661,2500,2000,1128,2500,0,2000
8976,3131,240000,2,2,2,34,0,0,0,0,...,97395,83314,73292,59270,10066,7255,3035,3030,3018,2012
8977,18598,150000,2,1,2,26,-1,-1,-1,-1,...,6701,54574,983,25580,5018,6701,54579,983,25580,26738
8978,6758,30000,1,2,2,24,0,0,0,-1,...,0,517,25420,24863,1545,0,1517,25420,0,980
8979,13425,70000,1,1,1,42,0,0,2,2,...,128391,125183,124527,125255,11100,4551,9,4230,4253,4545
8980,9340,30000,2,2,1,22,1,2,2,0,...,13296,12516,0,0,1000,0,0,0,0,0
8981,23043,160000,2,1,1,32,0,0,0,0,...,89231,67134,55773,46485,3805,2993,2293,1838,1687,2735
8982,855,50000,2,3,2,49,0,0,0,0,...,9366,8566,10066,0,2000,3000,1500,1500,0,0
8983,26008,100000,2,2,2,31,0,0,0,0,...,77919,79597,88685,87773,2750,2854,3000,10400,600,4254
8984,15912,200000,2,1,2,29,-2,-2,-2,-2,...,0,3941,16405,-150,0,0,3941,16405,0,2477
8985,10663,70000,1,1,2,40,2,2,0,0,...,45738,48977,52191,53242,0,1750,4000,4000,2060,2200
8986,16524,20000,1,3,2,24,0,0,0,0,...,18748,19627,19624,19652,1600,1357,1236,623,653,673
8987,12508,80000,2,2,1,24,0,0,0,2,...,54936,55735,56699,55632,3000,5000,2300,2000,0,2500
8988,2855,50000,2,2,2,25,2,2,2,2,...,17796,17213,18432,18981,1100,2150,0,1500,1000,0
8989,4881,250000,2,1,2,43,0,0,0,0,...,90901,69927,71403,69948,4409,3023,2600,2700,2801,2500
8990,18218,50000,1,2,3,52,0,0,0,0,...,50144,10683,9953,9567,2500,1500,1300,800,1000,1500
8991,778,20000,1,2,2,26,-1,-1,-1,-1,...,451,-810,-420,1320,1261,451,0,780,2130,0
8992,6728,220000,1,1,2,29,0,0,0,0,...,183838,157898,164860,168294,10110,12000,5852,10000,6610,5836
8993,1629,140000,2,3,1,31,2,2,2,2,...,91936,94623,94952,95234,5000,1800,5000,1900,4700,0
8994,19725,270000,2,2,2,28,0,0,0,0,...,27846,21787,16429,5488,6000,2000,1200,330,2000,8258
8995,16413,230000,2,2,1,42,-1,-1,-2,-2,...,0,0,0,0,0,0,0,0,0,0
8996,17210,90000,2,1,2,28,-1,-1,-1,-1,...,7956,499,0,5990,1950,7956,499,0,5990,0
8997,24002,60000,1,2,2,26,0,0,0,0,...,57416,55736,26958,28847,2282,2324,2049,2000,3000,1120
8998,17019,70000,2,2,2,23,0,0,0,0,...,47208,47241,48212,45849,2100,2079,2500,2000,2000,1700
8999,23415,600000,2,2,1,38,1,2,2,2,...,39635,35130,33229,32171,0,4000,0,1500,2000,3000

In [140]:
test_df.drop(['ID', 'EDUCATION', 'MARRIAGE', 'AGE'], axis = 1, inplace = True)
#test_df.drop(['ID'], axis = 1, inplace = True)
test_df[test_df['PAY_0'] ==-2]=-1
test_df[test_df['PAY_2'] ==-2]=-1
test_df[test_df['PAY_3'] ==-2]=-1
test_df[test_df['PAY_4'] ==-2]=-1
test_df[test_df['PAY_5'] ==-2]=-1
test_df[test_df['PAY_6'] ==-2]=-1
test_df[test_df['LIMIT_BAL'] ==-1]=0

In [141]:
X1.columns

Index(['LIMIT_BAL', 'SEX', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5',
       'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
       'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default_payment_next_month'],
      dtype='object')

In [142]:
test_df.columns

Index(['LIMIT_BAL', 'SEX', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5',
       'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
       'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object')

In [143]:
X_sub = test_df.iloc[:,0:19]
X_sub = mm_scaler.fit_transform(X_sub)

C:\Users\APOORV\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [144]:
X_sub

array([[0.06      , 1.        , 0.11111111, ..., 0.00153453, 0.00265269,
        0.00356365],
       [0.2       , 1.        , 0.11111111, ..., 0.02248784, 0.        ,
        0.01345512],
       [0.        , 0.        , 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.06      , 0.5       , 0.11111111, ..., 0.00228673, 0.00378145,
        0.00703352],
       [0.07      , 1.        , 0.11111111, ..., 0.00279005, 0.00378145,
        0.00468901],
       [0.6       , 1.        , 0.22222222, ..., 0.        , 0.00283609,
        0.00468901]])

In [145]:
y_pred_sub_log = logisticRegr.predict(X_sub)
predict_sub_mlp = mlp.predict(X_sub)

In [146]:
new_series_log = pd.Series(y_pred_sub_log)
new_series_mlp = pd.Series(predict_sub_mlp)

In [147]:
new_series_log.value_counts()

0    8317
1     683
dtype: int64

In [148]:
new_series_mlp.value_counts()

0    8388
1     612
dtype: int64

In [149]:
test_df_submit = pd.read_csv('test.csv')

In [150]:
test_df_submit

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,10178,60000,2,2,1,30,0,0,0,0,...,38117,38874,38667,39544,1628,1618,1375,1403,1520,1205
1,5304,200000,2,1,2,29,0,0,0,0,...,76593,93988,50292,10510,4160,14593,20150,0,5739,12050
2,5187,230000,1,1,2,39,0,0,0,0,...,20650,0,0,0,2500,2000,0,0,0,0
3,14495,150000,1,1,2,40,0,0,0,0,...,145978,139791,142745,146872,5800,5245,5200,5200,6500,7200
4,20444,140000,1,2,2,27,0,0,0,0,...,76230,77954,78953,81848,10000,10000,3393,3260,5000,3000
5,17667,210000,2,2,2,41,0,0,0,0,...,99865,77754,49529,30683,9000,4000,3018,2000,3000,3000
6,21211,50000,1,2,2,38,0,0,0,0,...,17266,18253,18618,37495,1266,1298,1285,650,825,1582
7,7178,500000,1,2,1,61,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
8,20783,300000,1,1,1,33,0,0,0,0,...,22396,21055,14714,7323,1514,1216,3127,3046,2011,142
9,24033,50000,1,2,2,25,0,0,2,2,...,43032,47242,46212,45205,14200,2100,5215,0,0,0
10,754,500000,2,2,2,43,-1,0,0,0,...,39032,29092,22725,11590,4006,2383,1126,782,596,1572
11,23732,30000,2,2,2,53,-1,-1,0,0,...,16863,7380,8580,10000,15700,2000,2000,1200,2200,0
12,6072,230000,2,2,1,41,0,0,0,0,...,172056,172615,174555,177010,8000,7500,6500,6500,7000,7068
13,17662,290000,2,2,1,49,-2,-2,-1,2,...,11764,11186,6863,6179,0,12000,0,0,0,0
14,5541,20000,2,1,2,23,0,0,0,2,...,17750,17175,18716,18782,1300,2180,0,1818,1000,680
15,22697,80000,2,2,2,36,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
16,29905,60000,1,3,2,30,0,0,0,0,...,54126,58732,59306,59728,2600,4553,5800,2000,1000,1462
17,6695,50000,1,2,2,24,0,0,0,0,...,8741,8911,8943,9140,1290,1294,464,324,345,500
18,12664,10000,1,3,2,28,2,0,0,-1,...,0,1170,9956,9992,1000,1600,1170,9956,282,91
19,15392,300000,2,2,2,42,0,0,0,0,...,108659,110781,107833,104466,5400,5800,6000,7000,5000,5000
20,309,30000,1,3,1,55,2,2,2,3,...,11339,12841,13836,14514,1200,1200,2000,1500,1500,1500
21,16129,200000,2,2,2,32,0,0,0,0,...,13683,-3942,123250,125926,1500,1000,0,128000,4600,5000
22,6324,100000,2,2,2,30,0,0,0,0,...,56058,51573,47665,43756,2801,2300,1613,1594,1654,1222
23,23673,130000,2,2,3,48,-1,-1,-1,2,...,109,109,109,0,0,109,0,0,0,0
24,28889,50000,2,3,2,46,0,0,0,0,...,8770,7251,15948,8838,2500,2127,1500,1000,1000,1000
25,17687,120000,2,2,1,34,0,0,0,0,...,114061,116067,116294,118759,4400,4137,4400,4320,4500,4600
26,27129,360000,1,1,2,34,0,0,0,0,...,366591,331833,288709,290583,15000,15502,13801,9852,10224,10010
27,8487,200000,2,2,2,26,-2,-2,-2,-2,...,2321,327194,6680,3963,1468,2321,163597,6680,3963,2514
28,10304,210000,2,1,1,51,-1,-1,-2,-2,...,0,0,0,0,0,0,0,0,0,0
29,14991,160000,1,3,2,27,1,2,-1,0,...,34073,15676,99436,90927,0,142848,1800,90000,3300,3400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8970,15036,200000,1,1,1,38,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
8971,27479,150000,1,3,2,51,-1,-1,-1,-1,...,2651,2465,4108,4703,3146,2659,2472,4116,4703,4708
8972,29685,280000,1,1,2,32,-2,-2,-2,-2,...,3735,13956,5911,1356,1355,3754,14025,12820,1362,5274
8973,4911,60000,2,1,2,34,2,-1,-1,0,...,823,683,240,998,240,823,0,240,998,223
8974,19213,90000,2,2,1,31,2,2,0,0,...,89779,89214,88847,88724,3500,4400,5013,4000,4000,4000
8975,508,180000,2,2,2,28,0,0,0,0,...,36696,35813,37893,34661,2500,2000,1128,2500,0,2000
8976,3131,240000,2,2,2,34,0,0,0,0,...,97395,83314,73292,59270,10066,7255,3035,3030,3018,2012
8977,18598,150000,2,1,2,26,-1,-1,-1,-1,...,6701,54574,983,25580,5018,6701,54579,983,25580,26738
8978,6758,30000,1,2,2,24,0,0,0,-1,...,0,517,25420,24863,1545,0,1517,25420,0,980
8979,13425,70000,1,1,1,42,0,0,2,2,...,128391,125183,124527,125255,11100,4551,9,4230,4253,4545
8980,9340,30000,2,2,1,22,1,2,2,0,...,13296,12516,0,0,1000,0,0,0,0,0
8981,23043,160000,2,1,1,32,0,0,0,0,...,89231,67134,55773,46485,3805,2993,2293,1838,1687,2735
8982,855,50000,2,3,2,49,0,0,0,0,...,9366,8566,10066,0,2000,3000,1500,1500,0,0
8983,26008,100000,2,2,2,31,0,0,0,0,...,77919,79597,88685,87773,2750,2854,3000,10400,600,4254
8984,15912,200000,2,1,2,29,-2,-2,-2,-2,...,0,3941,16405,-150,0,0,3941,16405,0,2477
8985,10663,70000,1,1,2,40,2,2,0,0,...,45738,48977,52191,53242,0,1750,4000,4000,2060,2200
8986,16524,20000,1,3,2,24,0,0,0,0,...,18748,19627,19624,19652,1600,1357,1236,623,653,673
8987,12508,80000,2,2,1,24,0,0,0,2,...,54936,55735,56699,55632,3000,5000,2300,2000,0,2500
8988,2855,50000,2,2,2,25,2,2,2,2,...,17796,17213,18432,18981,1100,2150,0,1500,1000,0
8989,4881,250000,2,1,2,43,0,0,0,0,...,90901,69927,71403,69948,4409,3023,2600,2700,2801,2500
8990,18218,50000,1,2,3,52,0,0,0,0,...,50144,10683,9953,9567,2500,1500,1300,800,1000,1500
8991,778,20000,1,2,2,26,-1,-1,-1,-1,...,451,-810,-420,1320,1261,451,0,780,2130,0
8992,6728,220000,1,1,2,29,0,0,0,0,...,183838,157898,164860,168294,10110,12000,5852,10000,6610,5836
8993,1629,140000,2,3,1,31,2,2,2,2,...,91936,94623,94952,95234,5000,1800,5000,1900,4700,0
8994,19725,270000,2,2,2,28,0,0,0,0,...,27846,21787,16429,5488,6000,2000,1200,330,2000,8258
8995,16413,230000,2,2,1,42,-1,-1,-2,-2,...,0,0,0,0,0,0,0,0,0,0
8996,17210,90000,2,1,2,28,-1,-1,-1,-1,...,7956,499,0,5990,1950,7956,499,0,5990,0
8997,24002,60000,1,2,2,26,0,0,0,0,...,57416,55736,26958,28847,2282,2324,2049,2000,3000,1120
8998,17019,70000,2,2,2,23,0,0,0,0,...,47208,47241,48212,45849,2100,2079,2500,2000,2000,1700
8999,23415,600000,2,2,1,38,1,2,2,2,...,39635,35130,33229,32171,0,4000,0,1500,2000,3000

In [154]:
data = {'ID':test_df_submit.ID, 'default_payment_next_month':new_series_log}

In [155]:
submission = pd.DataFrame(data, columns = ['ID','default_payment_next_month'])

In [156]:
submission.to_csv(r'submission.csv', index = False)

In [115]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.

In [216]:
model = Sequential()
model.add(Dense(12, input_dim=18, activation='relu'))
model.add(Dense(18, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=150, batch_size=10)
_, accuracy = model.evaluate(X_train, y_train)
print('Accuracy: %.2f' % (accuracy*100))

WARNING:tensorflow:From C:\Users\APOORV\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

Epoch 1/150
21000/21000 [==============================] - 3s 140us/step - loss: 0.4093 - acc: 0.8414
Epoch 2/150
21000/21000 [==============================] - 3s 122us/step - loss: 0.3752 - acc: 0.8536
Epoch 3/150
21000/21000 [==============================] - 3s 121us/step - loss: 0.3689 - acc: 0.8573
Epoch 4/150
21000/21000 [==============================] - 2s 103us/step - loss: 0.3655 - acc: 0.8599
Epoch 5/150
21000/21000 [==============================] - 2s 110us/step - loss: 0.3636 - acc: 0.8615
Epoch 6/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3622 - acc: 0.8596
Epoch 7/150
21000/21000 [==============================] - 2s 97us/step - loss: 0.3612 - acc: 0.8598
Epoch 8/150
21000/21000 [==============================] - 2s 104us/step - loss: 0.3599 - acc: 0.8614
Epoch 9/150
21000/21000 [==============================] - 3s 123us/step - loss: 0.3587 - acc: 0.8597
Epoch 10/150
21000/21000 [==============================] - 2s 103us/step - loss: 0.3578 - acc: 0.8605
Epoch 11/150
21000/21000 [==============================] - 2s 106us/step - loss: 0.3565 - acc: 0.8608
Epoch 12/150
21000/21000 [==============================] - 2s 109us/step - loss: 0.3554 - acc: 0.8615
Epoch 13/150
21000/21000 [==============================] - 2s 110us/step - loss: 0.3536 - acc: 0.8602
Epoch 14/150
21000/21000 [==============================] - 2s 102us/step - loss: 0.3528 - acc: 0.8612
Epoch 15/150
21000/21000 [==============================] - 2s 102us/step - loss: 0.3513 - acc: 0.8600
Epoch 16/150
21000/21000 [==============================] - 2s 118us/step - loss: 0.3506 - acc: 0.8596
Epoch 17/150
21000/21000 [==============================] - 2s 109us/step - loss: 0.3492 - acc: 0.8617
Epoch 18/150
21000/21000 [==============================] - 2s 98us/step - loss: 0.3490 - acc: 0.8613
Epoch 19/150
21000/21000 [==============================] - 3s 121us/step - loss: 0.3483 - acc: 0.8610
Epoch 20/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3479 - acc: 0.8600
Epoch 21/150
21000/21000 [==============================] - 2s 101us/step - loss: 0.3472 - acc: 0.8599
Epoch 22/150
21000/21000 [==============================] - 2s 101us/step - loss: 0.3464 - acc: 0.8600
Epoch 23/150
21000/21000 [==============================] - 2s 109us/step - loss: 0.3460 - acc: 0.8603
Epoch 24/150
21000/21000 [==============================] - 2s 107us/step - loss: 0.3452 - acc: 0.8604
Epoch 25/150
21000/21000 [==============================] - 2s 112us/step - loss: 0.3446 - acc: 0.8603
Epoch 26/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3441 - acc: 0.8605
Epoch 27/150
21000/21000 [==============================] - 2s 101us/step - loss: 0.3437 - acc: 0.8610
Epoch 28/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3427 - acc: 0.8607
Epoch 29/150
21000/21000 [==============================] - 2s 104us/step - loss: 0.3427 - acc: 0.8611
Epoch 30/150
21000/21000 [==============================] - 2s 117us/step - loss: 0.3423 - acc: 0.8618
Epoch 31/150
21000/21000 [==============================] - 2s 116us/step - loss: 0.3413 - acc: 0.8623
Epoch 32/150
21000/21000 [==============================] - 2s 103us/step - loss: 0.3413 - acc: 0.8609
Epoch 33/150
21000/21000 [==============================] - 2s 98us/step - loss: 0.3411 - acc: 0.8611
Epoch 34/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3410 - acc: 0.8628
Epoch 35/150
21000/21000 [==============================] - 2s 97us/step - loss: 0.3408 - acc: 0.8603
Epoch 36/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3405 - acc: 0.8616
Epoch 37/150
21000/21000 [==============================] - 2s 97us/step - loss: 0.3402 - acc: 0.8614
Epoch 38/150
21000/21000 [==============================] - 2s 117us/step - loss: 0.3404 - acc: 0.8606
Epoch 39/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3389 - acc: 0.8618
Epoch 40/150
21000/21000 [==============================] - 2s 103us/step - loss: 0.3392 - acc: 0.8614
Epoch 41/150
21000/21000 [==============================] - 2s 96us/step - loss: 0.3388 - acc: 0.8619
Epoch 42/150
21000/21000 [==============================] - 2s 97us/step - loss: 0.3390 - acc: 0.8620
Epoch 43/150
21000/21000 [==============================] - 2s 98us/step - loss: 0.3387 - acc: 0.8610
Epoch 44/150
21000/21000 [==============================] - 2s 101us/step - loss: 0.3384 - acc: 0.8606
Epoch 45/150
21000/21000 [==============================] - 2s 104us/step - loss: 0.3384 - acc: 0.8611
Epoch 46/150
21000/21000 [==============================] - 2s 105us/step - loss: 0.3383 - acc: 0.8607
Epoch 47/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3375 - acc: 0.8607
Epoch 48/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3372 - acc: 0.8614
Epoch 49/150
21000/21000 [==============================] - 2s 98us/step - loss: 0.3372 - acc: 0.8605
Epoch 50/150
21000/21000 [==============================] - 2s 105us/step - loss: 0.3373 - acc: 0.8609
Epoch 51/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3363 - acc: 0.8614
Epoch 52/150
21000/21000 [==============================] - 2s 104us/step - loss: 0.3371 - acc: 0.8610
Epoch 53/150
21000/21000 [==============================] - 2s 111us/step - loss: 0.3365 - acc: 0.8622
Epoch 54/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3365 - acc: 0.8605
Epoch 55/150
21000/21000 [==============================] - 2s 98us/step - loss: 0.3369 - acc: 0.8606
Epoch 56/150
21000/21000 [==============================] - 2s 98us/step - loss: 0.3362 - acc: 0.8614
Epoch 57/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3357 - acc: 0.8612
Epoch 58/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3359 - acc: 0.8618
Epoch 59/150
21000/21000 [==============================] - 2s 103us/step - loss: 0.3353 - acc: 0.8621
Epoch 60/150
21000/21000 [==============================] - 2s 105us/step - loss: 0.3354 - acc: 0.8612
Epoch 61/150
21000/21000 [==============================] - 2s 115us/step - loss: 0.3353 - acc: 0.8613
Epoch 62/150
21000/21000 [==============================] - 2s 109us/step - loss: 0.3350 - acc: 0.8608
Epoch 63/150
21000/21000 [==============================] - 2s 103us/step - loss: 0.3352 - acc: 0.8614
Epoch 64/150
21000/21000 [==============================] - 2s 98us/step - loss: 0.3348 - acc: 0.8614
Epoch 65/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3342 - acc: 0.8608
Epoch 66/150
21000/21000 [==============================] - 2s 102us/step - loss: 0.3343 - acc: 0.8618
Epoch 67/150
21000/21000 [==============================] - 2s 104us/step - loss: 0.3352 - acc: 0.8611
Epoch 68/150
21000/21000 [==============================] - 2s 113us/step - loss: 0.3345 - acc: 0.8618
Epoch 69/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3349 - acc: 0.8617
Epoch 70/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3344 - acc: 0.8614
Epoch 71/150
21000/21000 [==============================] - 2s 101us/step - loss: 0.3341 - acc: 0.8610
Epoch 72/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3341 - acc: 0.8630
Epoch 73/150
21000/21000 [==============================] - 2s 110us/step - loss: 0.3345 - acc: 0.8620
Epoch 74/150
21000/21000 [==============================] - 2s 98us/step - loss: 0.3333 - acc: 0.8617
Epoch 75/150
21000/21000 [==============================] - 2s 116us/step - loss: 0.3339 - acc: 0.8616
Epoch 76/150
21000/21000 [==============================] - 2s 107us/step - loss: 0.3341 - acc: 0.8609
Epoch 77/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3340 - acc: 0.8619
Epoch 78/150
21000/21000 [==============================] - 2s 101us/step - loss: 0.3333 - acc: 0.8621

Epoch 79/150
21000/21000 [==============================] - 3s 127us/step - loss: 0.3332 - acc: 0.8624
Epoch 80/150
21000/21000 [==============================] - 3s 132us/step - loss: 0.3334 - acc: 0.8618
Epoch 81/150
21000/21000 [==============================] - 3s 131us/step - loss: 0.3336 - acc: 0.8616
Epoch 82/150
21000/21000 [==============================] - 3s 134us/step - loss: 0.3336 - acc: 0.8618
Epoch 83/150
21000/21000 [==============================] - 3s 125us/step - loss: 0.3332 - acc: 0.8619
Epoch 84/150
21000/21000 [==============================] - 3s 134us/step - loss: 0.3334 - acc: 0.8613
Epoch 85/150
21000/21000 [==============================] - 3s 129us/step - loss: 0.3337 - acc: 0.8622
Epoch 86/150
21000/21000 [==============================] - 3s 132us/step - loss: 0.3337 - acc: 0.8617
Epoch 87/150
21000/21000 [==============================] - 3s 136us/step - loss: 0.3333 - acc: 0.8610
Epoch 88/150
21000/21000 [==============================] - 3s 137us/step - loss: 0.3330 - acc: 0.8619
Epoch 89/150
21000/21000 [==============================] - 3s 140us/step - loss: 0.3331 - acc: 0.8612
Epoch 90/150
21000/21000 [==============================] - 3s 132us/step - loss: 0.3330 - acc: 0.8624
Epoch 91/150
21000/21000 [==============================] - 3s 128us/step - loss: 0.3332 - acc: 0.8615
Epoch 92/150
21000/21000 [==============================] - 3s 130us/step - loss: 0.3328 - acc: 0.8619
Epoch 93/150
21000/21000 [==============================] - 3s 133us/step - loss: 0.3326 - acc: 0.8619
Epoch 94/150
21000/21000 [==============================] - 3s 128us/step - loss: 0.3330 - acc: 0.8610
Epoch 95/150
21000/21000 [==============================] - 3s 126us/step - loss: 0.3327 - acc: 0.8614
Epoch 96/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3325 - acc: 0.8619
Epoch 97/150
21000/21000 [==============================] - 2s 94us/step - loss: 0.3321 - acc: 0.8623
Epoch 98/150
21000/21000 [==============================] - 2s 94us/step - loss: 0.3323 - acc: 0.8630
Epoch 99/150
21000/21000 [==============================] - 2s 106us/step - loss: 0.3324 - acc: 0.8620
Epoch 100/150
21000/21000 [==============================] - 2s 107us/step - loss: 0.3323 - acc: 0.8622
Epoch 101/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3324 - acc: 0.8612
Epoch 102/150
21000/21000 [==============================] - 2s 106us/step - loss: 0.3320 - acc: 0.8621
Epoch 103/150
21000/21000 [==============================] - 2s 106us/step - loss: 0.3317 - acc: 0.8614
Epoch 104/150
21000/21000 [==============================] - 2s 106us/step - loss: 0.3323 - acc: 0.8617
Epoch 105/150
21000/21000 [==============================] - 2s 101us/step - loss: 0.3316 - acc: 0.8624
Epoch 106/150
21000/21000 [==============================] - 2s 116us/step - loss: 0.3320 - acc: 0.8629
Epoch 107/150
21000/21000 [==============================] - 2s 115us/step - loss: 0.3320 - acc: 0.8616
Epoch 108/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3322 - acc: 0.8618
Epoch 109/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3315 - acc: 0.8619
Epoch 110/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3324 - acc: 0.8611
Epoch 111/150
21000/21000 [==============================] - 2s 93us/step - loss: 0.3319 - acc: 0.8618
Epoch 112/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3315 - acc: 0.8603
Epoch 113/150
21000/21000 [==============================] - 2s 107us/step - loss: 0.3315 - acc: 0.8616
Epoch 114/150
21000/21000 [==============================] - 2s 98us/step - loss: 0.3313 - acc: 0.8628
Epoch 115/150
21000/21000 [==============================] - 2s 102us/step - loss: 0.3313 - acc: 0.8632
Epoch 116/150
21000/21000 [==============================] - 2s 96us/step - loss: 0.3315 - acc: 0.8619
Epoch 117/150
21000/21000 [==============================] - 2s 106us/step - loss: 0.3313 - acc: 0.8617
Epoch 118/150
21000/21000 [==============================] - 2s 102us/step - loss: 0.3316 - acc: 0.8622
Epoch 119/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3314 - acc: 0.8626
Epoch 120/150
21000/21000 [==============================] - 2s 97us/step - loss: 0.3312 - acc: 0.8605
Epoch 121/150
21000/21000 [==============================] - 2s 97us/step - loss: 0.3314 - acc: 0.8620
Epoch 122/150
21000/21000 [==============================] - 2s 101us/step - loss: 0.3312 - acc: 0.8620
Epoch 123/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3310 - acc: 0.8624
Epoch 124/150
21000/21000 [==============================] - 2s 96us/step - loss: 0.3310 - acc: 0.8629
Epoch 125/150
21000/21000 [==============================] - 2s 98us/step - loss: 0.3309 - acc: 0.8620
Epoch 126/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3311 - acc: 0.8616
Epoch 127/150
21000/21000 [==============================] - 2s 93us/step - loss: 0.3311 - acc: 0.8627
Epoch 128/150
21000/21000 [==============================] - 2s 97us/step - loss: 0.3304 - acc: 0.8620
Epoch 129/150
21000/21000 [==============================] - 2s 94us/step - loss: 0.3310 - acc: 0.8628
Epoch 130/150
21000/21000 [==============================] - 2s 102us/step - loss: 0.3305 - acc: 0.8615
Epoch 131/150
21000/21000 [==============================] - 2s 103us/step - loss: 0.3317 - acc: 0.8621
Epoch 132/150
21000/21000 [==============================] - 2s 103us/step - loss: 0.3309 - acc: 0.8625
Epoch 133/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3307 - acc: 0.8611
Epoch 134/150
21000/21000 [==============================] - 2s 102us/step - loss: 0.3309 - acc: 0.8615
Epoch 135/150
21000/21000 [==============================] - 2s 100us/step - loss: 0.3306 - acc: 0.8618
Epoch 136/150
21000/21000 [==============================] - 2s 99us/step - loss: 0.3306 - acc: 0.8617
Epoch 137/150
21000/21000 [==============================] - 2s 103us/step - loss: 0.3300 - acc: 0.8629
Epoch 138/150
21000/21000 [==============================] - 2s 115us/step - loss: 0.3301 - acc: 0.8626
Epoch 139/150
21000/21000 [==============================] - 2s 111us/step - loss: 0.3307 - acc: 0.8635
Epoch 140/150
21000/21000 [==============================] - 3s 126us/step - loss: 0.3310 - acc: 0.8626
Epoch 141/150
21000/21000 [==============================] - 2s 105us/step - loss: 0.3301 - acc: 0.8622
Epoch 142/150
21000/21000 [==============================] - 3s 135us/step - loss: 0.3299 - acc: 0.8630
Epoch 143/150
21000/21000 [==============================] - 4s 180us/step - loss: 0.3300 - acc: 0.8624
Epoch 144/150
21000/21000 [==============================] - 4s 187us/step - loss: 0.3302 - acc: 0.8628
Epoch 145/150
21000/21000 [==============================] - 4s 170us/step - loss: 0.3304 - acc: 0.8633
Epoch 146/150
21000/21000 [==============================] - 3s 160us/step - loss: 0.3300 - acc: 0.8638
Epoch 147/150
21000/21000 [==============================] - 3s 120us/step - loss: 0.3300 - acc: 0.8622
Epoch 148/150
21000/21000 [==============================] - 4s 173us/step - loss: 0.3302 - acc: 0.8631
Epoch 149/150
21000/21000 [==============================] - 3s 136us/step - loss: 0.3301 - acc: 0.8627
Epoch 150/150
21000/21000 [==============================] - 3s 141us/step - loss: 0.3300 - acc: 0.8621
16800/16800 [==============================] - 0s 23us/step
Accuracy: 86.46

In [227]:
predict_nn_sub = model.predict(X_sub)
rounded = [round(x[0]) for x in predict_nn_sub]

In [223]:
new_series_nn = predict_nn_sub.flatten()

In [228]:
new_series_nn1 = pd.Series(rounded)

In [229]:
new_series_nn1.value_counts()

0.0    8254
1.0     746
dtype: int64

In [230]:
data = {'ID':test_df_submit.ID, 'default_payment_next_month':new_series_nn1}
submission = pd.DataFrame(data, columns = ['ID','default_payment_next_month'])
submission.to_csv(r'submission_nn.csv', index = False)

# ENSEMBLE OF XGBOOST, CATBOOST, LGBM

In [17]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [18]:
combine = train.append(test)
combine.shape

(30000, 25)

In [19]:
print(combine.isnull().sum())
print(combine.dtypes)

ID                               0
LIMIT_BAL                        0
SEX                              0
EDUCATION                        0
MARRIAGE                         0
AGE                              0
PAY_0                            0
PAY_2                            0
PAY_3                            0
PAY_4                            0
PAY_5                            0
PAY_6                            0
BILL_AMT1                        0
BILL_AMT2                        0
BILL_AMT3                        0
BILL_AMT4                        0
BILL_AMT5                        0
BILL_AMT6                        0
PAY_AMT1                         0
PAY_AMT2                         0
PAY_AMT3                         0
PAY_AMT4                         0
PAY_AMT5                         0
PAY_AMT6                         0
default_payment_next_month    9000
dtype: int64
ID                              int64
LIMIT_BAL                       int64
SEX                             int64
EDUCATION                       int64
MARRIAGE                        int64
AGE                             int64
PAY_0                           int64
PAY_2                           int64
PAY_3                           int64
PAY_4                           int64
PAY_5                           int64
PAY_6                           int64
BILL_AMT1                       int64
BILL_AMT2                       int64
BILL_AMT3                       int64
BILL_AMT4                       int64
BILL_AMT5                       int64
BILL_AMT6                       int64
PAY_AMT1                        int64
PAY_AMT2                        int64
PAY_AMT3                        int64
PAY_AMT4                        int64
PAY_AMT5                        int64
PAY_AMT6                        int64
default_payment_next_month    float64
dtype: object

In [20]:
combine['LIMIT_BAL'].describe()

count      30000.000000
mean      167484.322667
std       129747.661567
min        10000.000000
25%        50000.000000
50%       140000.000000
75%       240000.000000
max      1000000.000000
Name: LIMIT_BAL, dtype: float64

In [21]:
combine['LIMIT_BAL'] = np.log(combine['LIMIT_BAL'])
combine['LIMIT_BAL'].describe()

count    30000.000000
mean        11.663002
std          0.941135
min          9.210340
25%         10.819778
50%         11.849398
75%         12.388394
max         13.815511
Name: LIMIT_BAL, dtype: float64

In [22]:
combine['SEX'] = combine['SEX'].replace(1, "Male")
combine['SEX'] = combine['SEX'].replace(2, "Female")
combine['SEX'].value_counts()

Female    18112
Male      11888
Name: SEX, dtype: int64

In [23]:
combine['EDUCATION'].value_counts()

2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: EDUCATION, dtype: int64

In [24]:
combine['EDUCATION'] = combine['EDUCATION'].replace(1, "Graduate_School")
combine['EDUCATION'] = combine['EDUCATION'].replace(2, "University")
combine['EDUCATION'] = combine['EDUCATION'].replace(3, "High_School")
combine['EDUCATION'] = combine['EDUCATION'].replace(4, "Unknown")
combine['EDUCATION'] = combine['EDUCATION'].replace(5, "Unknown")
combine['EDUCATION'] = combine['EDUCATION'].replace(6, "Unknown")
combine['EDUCATION'] = combine['EDUCATION'].replace(0, "Unknown")
combine['EDUCATION'].value_counts()

University         14030
Graduate_School    10585
High_School         4917
Unknown              468
Name: EDUCATION, dtype: int64

In [25]:
combine['MARRIAGE'].value_counts()

2    15964
1    13659
3      323
0       54
Name: MARRIAGE, dtype: int64

In [26]:
combine['MARRIAGE'] = combine['MARRIAGE'].replace(1, "Married")
combine['MARRIAGE'] = combine['MARRIAGE'].replace(2, "Single")
combine['MARRIAGE'] = combine['MARRIAGE'].replace(3, "Divorced")
combine['MARRIAGE'] = combine['MARRIAGE'].replace(0, "Unknown")
combine['MARRIAGE'].value_counts()

Single      15964
Married     13659
Divorced      323
Unknown        54
Name: MARRIAGE, dtype: int64

In [27]:
combine['AGE'].describe()

count    30000.000000
mean        35.485500
std          9.217904
min         21.000000
25%         28.000000
50%         34.000000
75%         41.000000
max         79.000000
Name: AGE, dtype: float64

In [28]:
bins= [20,30,40,50,60,70,80]
labels = ['Age_Tier1','Age_Tier2','Age_Tier3','Age_Tier4','Age_Tier5','Age_Tier6']
combine['AGE'] = pd.cut(combine['AGE'], bins=bins, labels=labels, right=False)
combine['AGE'].value_counts()

Age_Tier2    11238
Age_Tier1     9618
Age_Tier3     6464
Age_Tier4     2341
Age_Tier5      314
Age_Tier6       25
Name: AGE, dtype: int64

In [30]:
# combine['PAY_0'].value_counts()
combine['PAY_0'] = combine['PAY_0'].replace(0, "Paid_On_Time")
combine['PAY_0'] = combine['PAY_0'].replace(-1, "Duly_1")
combine['PAY_0'] = combine['PAY_0'].replace(1, "Delay_1")
combine['PAY_0'] = combine['PAY_0'].replace(-2, "Duly_2")
combine['PAY_0'] = combine['PAY_0'].replace(2, "Delay_2")
combine['PAY_0'] = combine['PAY_0'].replace(3, "Delay_3")
combine['PAY_0'] = combine['PAY_0'].replace(4, "Delay_4")
combine['PAY_0'] = combine['PAY_0'].replace(5, "Delay_5")
combine['PAY_0'] = combine['PAY_0'].replace(8, "Delay_8")
combine['PAY_0'] = combine['PAY_0'].replace(6, "Delay_6")
combine['PAY_0'] = combine['PAY_0'].replace(7, "Delay_7")
combine['PAY_0'].value_counts()

Paid_On_Time    14737
Duly_1           5686
Delay_1          3688
Duly_2           2759
Delay_2          2667
Delay_3           322
Delay_4            76
Delay_5            26
Delay_8            19
Delay_6            11
Delay_7             9
Name: PAY_0, dtype: int64

In [32]:
# combine['PAY_2'].value_counts()
combine['PAY_2'] = combine['PAY_2'].replace(0, "Paid_On_Time")
combine['PAY_2'] = combine['PAY_2'].replace(-1, "Duly_1")
combine['PAY_2'] = combine['PAY_2'].replace(1, "Delay_1")
combine['PAY_2'] = combine['PAY_2'].replace(-2, "Duly_2")
combine['PAY_2'] = combine['PAY_2'].replace(2, "Delay_2")
combine['PAY_2'] = combine['PAY_2'].replace(3, "Delay_3")
combine['PAY_2'] = combine['PAY_2'].replace(4, "Delay_4")
combine['PAY_2'] = combine['PAY_2'].replace(5, "Delay_5")
combine['PAY_2'] = combine['PAY_2'].replace(8, "Delay_8")
combine['PAY_2'] = combine['PAY_2'].replace(6, "Delay_6")
combine['PAY_2'] = combine['PAY_2'].replace(7, "Delay_7")
combine['PAY_2'].value_counts()

Paid_On_Time    15730
Duly_1           6050
Delay_2          3927
Duly_2           3782
Delay_3           326
Delay_4            99
Delay_1            28
Delay_5            25
Delay_7            20
Delay_6            12
Delay_8             1
Name: PAY_2, dtype: int64

In [34]:
# combine['PAY_3'].value_counts()
combine['PAY_3'] = combine['PAY_3'].replace(0, "Paid_On_Time")
combine['PAY_3'] = combine['PAY_3'].replace(-1, "Duly_1")
combine['PAY_3'] = combine['PAY_3'].replace(1, "Delay_1")
combine['PAY_3'] = combine['PAY_3'].replace(-2, "Duly_2")
combine['PAY_3'] = combine['PAY_3'].replace(2, "Delay_2")
combine['PAY_3'] = combine['PAY_3'].replace(3, "Delay_3")
combine['PAY_3'] = combine['PAY_3'].replace(4, "Delay_4")
combine['PAY_3'] = combine['PAY_3'].replace(5, "Delay_5")
combine['PAY_3'] = combine['PAY_3'].replace(8, "Delay_8")
combine['PAY_3'] = combine['PAY_3'].replace(6, "Delay_6")
combine['PAY_3'] = combine['PAY_3'].replace(7, "Delay_7")
combine['PAY_3'].value_counts()

Paid_On_Time    15764
Duly_1           5938
Duly_2           4085
Delay_2          3819
Delay_3           240
Delay_4            76
Delay_7            27
Delay_6            23
Delay_5            21
Delay_1             4
Delay_8             3
Name: PAY_3, dtype: int64

In [35]:
# combine['PAY_4'].value_counts()
combine['PAY_4'] = combine['PAY_4'].replace(0, "Paid_On_Time")
combine['PAY_4'] = combine['PAY_4'].replace(-1, "Duly_1")
combine['PAY_4'] = combine['PAY_4'].replace(1, "Delay_1")
combine['PAY_4'] = combine['PAY_4'].replace(-2, "Duly_2")
combine['PAY_4'] = combine['PAY_4'].replace(2, "Delay_2")
combine['PAY_4'] = combine['PAY_4'].replace(3, "Delay_3")
combine['PAY_4'] = combine['PAY_4'].replace(4, "Delay_4")
combine['PAY_4'] = combine['PAY_4'].replace(5, "Delay_5")
combine['PAY_4'] = combine['PAY_4'].replace(8, "Delay_8")
combine['PAY_4'] = combine['PAY_4'].replace(6, "Delay_6")
combine['PAY_4'] = combine['PAY_4'].replace(7, "Delay_7")
combine['PAY_4'].value_counts()

Paid_On_Time    16455
Duly_1           5687
Duly_2           4348
Delay_2          3159
Delay_3           180
Delay_4            69
Delay_7            58
Delay_5            35
Delay_6             5
Delay_8             2
Delay_1             2
Name: PAY_4, dtype: int64

In [36]:
# combine['PAY_5'].value_counts()
combine['PAY_5'] = combine['PAY_5'].replace(0, "Paid_On_Time")
combine['PAY_5'] = combine['PAY_5'].replace(-1, "Duly_1")
combine['PAY_5'] = combine['PAY_5'].replace(1, "Delay_1")
combine['PAY_5'] = combine['PAY_5'].replace(-2, "Duly_2")
combine['PAY_5'] = combine['PAY_5'].replace(2, "Delay_2")
combine['PAY_5'] = combine['PAY_5'].replace(3, "Delay_3")
combine['PAY_5'] = combine['PAY_5'].replace(4, "Delay_4")
combine['PAY_5'] = combine['PAY_5'].replace(5, "Delay_5")
combine['PAY_5'] = combine['PAY_5'].replace(8, "Delay_8")
combine['PAY_5'] = combine['PAY_5'].replace(6, "Delay_6")
combine['PAY_5'] = combine['PAY_5'].replace(7, "Delay_7")
combine['PAY_5'].value_counts()

Paid_On_Time    16947
Duly_1           5539
Duly_2           4546
Delay_2          2626
Delay_3           178
Delay_4            84
Delay_7            58
Delay_5            17
Delay_6             4
Delay_8             1
Name: PAY_5, dtype: int64

In [37]:
# combine['PAY_6'].value_counts()
combine['PAY_6'] = combine['PAY_6'].replace(0, "Paid_On_Time")
combine['PAY_6'] = combine['PAY_6'].replace(-1, "Duly_1")
combine['PAY_6'] = combine['PAY_6'].replace(1, "Delay_1")
combine['PAY_6'] = combine['PAY_6'].replace(-2, "Duly_2")
combine['PAY_6'] = combine['PAY_6'].replace(2, "Delay_2")
combine['PAY_6'] = combine['PAY_6'].replace(3, "Delay_3")
combine['PAY_6'] = combine['PAY_6'].replace(4, "Delay_4")
combine['PAY_6'] = combine['PAY_6'].replace(5, "Delay_5")
combine['PAY_6'] = combine['PAY_6'].replace(8, "Delay_8")
combine['PAY_6'] = combine['PAY_6'].replace(6, "Delay_6")
combine['PAY_6'] = combine['PAY_6'].replace(7, "Delay_7")
combine['PAY_6'].value_counts()

Paid_On_Time    16286
Duly_1           5740
Duly_2           4895
Delay_2          2766
Delay_3           184
Delay_4            49
Delay_7            46
Delay_6            19
Delay_5            13
Delay_8             2
Name: PAY_6, dtype: int64

In [38]:
bill_amount = ['BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6']
combine[bill_amount].describe()

,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6
count,30000.000000,30000.000000,3.000000e+04,30000.000000,30000.000000,30000.000000
mean,51223.330900,49179.075167,4.701315e+04,43262.948967,40311.400967,38871.760400
std,73635.860576,71173.768783,6.934939e+04,64332.856134,60797.155770,59554.107537
min,-165580.000000,-69777.000000,-1.572640e+05,-170000.000000,-81334.000000,-339603.000000
25%,3558.750000,2984.750000,2.666250e+03,2326.750000,1763.000000,1256.000000
50%,22381.500000,21200.000000,2.008850e+04,19052.000000,18104.500000,17071.000000
75%,67091.000000,64006.250000,6.016475e+04,54506.000000,50190.500000,49198.250000
max,964511.000000,983931.000000,1.664089e+06,891586.000000,927171.000000,961664.000000

In [39]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

combine[bill_amount] = scaler.fit_transform(combine[bill_amount])
combine[bill_amount].describe()

,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6
count,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04
mean,-1.089499e-17,-4.310626e-17,4.736952e-17,5.826450e-17,-2.368476e-17,1.042129e-17
std,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00
min,-2.944312e+00,-1.671375e+00,-2.945672e+00,-3.315048e+00,-2.000874e+00,-6.355247e+00
25%,-6.473120e-01,-6.490466e-01,-6.394814e-01,-6.363293e-01,-6.340600e-01,-6.316338e-01
50%,-3.916884e-01,-3.931159e-01,-3.882529e-01,-3.763451e-01,-3.652683e-01,-3.660725e-01
75%,2.154919e-01,2.083271e-01,1.896457e-01,1.747667e-01,1.624955e-01,1.733997e-01
max,1.240296e+01,1.313360e+01,2.331820e+01,1.318669e+01,1.458743e+01,1.549528e+01

In [40]:
pay_amount = ['PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6']
combine[pay_amount].describe()

,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
count,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000
mean,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567
std,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775
min,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000
25%,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000
50%,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000
75%,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000
max,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000

In [41]:
combine[pay_amount] = scaler.fit_transform(combine[pay_amount])
combine[pay_amount].describe()

,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
count,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04
mean,-4.855375e-18,1.432928e-17,2.155313e-17,9.473903e-18,-1.776357e-17,-1.800042e-17
std,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00,1.000017e+00
min,-3.419416e-01,-2.569895e-01,-2.968013e-01,-3.080626e-01,-3.141361e-01,-2.933821e-01
25%,-2.815661e-01,-2.208358e-01,-2.746506e-01,-2.891680e-01,-2.976091e-01,-2.867584e-01
50%,-2.151530e-01,-1.697952e-01,-1.945673e-01,-2.123132e-01,-2.159561e-01,-2.090042e-01
75%,-3.970176e-02,-3.998021e-02,-4.093230e-02,-5.188511e-02,-5.026084e-02,-6.837436e-02
max,5.239921e+01,7.284299e+01,5.059528e+01,3.933218e+01,2.760363e+01,2.944510e+01

In [42]:
combine = pd.get_dummies(combine)
combine.shape

(30000, 95)

In [43]:
X = combine[combine['default_payment_next_month'].isnull()!=True].drop(['ID','default_payment_next_month'], axis=1)
y = combine[combine['default_payment_next_month'].isnull()!=True]['default_payment_next_month']

X_test = combine[combine['default_payment_next_month'].isnull()==True].drop(['ID','default_payment_next_month'], axis=1)

X.shape, y.shape, X_test.shape

((21000, 93), (21000,), (9000, 93))

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(X, y, test_size=0.2)
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=20,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=20,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
model.fit(x_train,y_train)

pred_y = model.predict_proba(x_val)[:,1]

/home/apoorv/anaconda3/envs/my_env/lib/python3.7/site-packages/sklearn/tree/_classes.py:327: FutureWarning: The parameter 'presort' is deprecated and has no effect. It will be removed in v0.24. You can suppress this warning by not passing any value to the 'presort' parameter.
  FutureWarning)

In [45]:
from lightgbm import LGBMClassifier
model = LGBMClassifier(n_estimator=5000,
                       random_state=1994,
                       learning_rate=0.05,
                       reg_alpha=0.2,
                       colsample_bytree=0.5,
                       bagging_fraction=0.9)

model.fit(x_train,y_train,
          eval_set=[(x_train,y_train),(x_val, y_val.values)],
          eval_metric='auc',
          early_stopping_rounds=100,
          verbose=200)

pred_y = model.predict_proba(x_val)[:,1]

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[100]	training's auc: 0.858428	training's binary_logloss: 0.377509	valid_1's auc: 0.782538	valid_1's binary_logloss: 0.431002

In [46]:
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score
print(roc_auc_score(y_val, pred_y))
confusion_matrix(y_val,pred_y>0.5)

0.7825377790710168

array([[3076,  185],
       [ 581,  358]])

In [47]:
err = []
y_pred_tot_lgm = []

from sklearn.model_selection import StratifiedKFold

fold = StratifiedKFold(n_splits=10,shuffle=True,random_state=1994)
i = 1
for train_index, test_index in fold.split(X, y):
    x_train, x_val = X.iloc[train_index], X.iloc[test_index]
    y_train, y_val = y[train_index], y[test_index]
    m = LGBMClassifier(boosting_type='gbdt',
                       max_depth=5,
                       learning_rate=0.08,
                       n_estimators=5000,
                       min_child_weight=0.01,
                       colsample_bytree=0.5,
                       random_state=1994)
    m.fit(x_train, y_train,
          eval_set=[(x_train,y_train),(x_val, y_val)],
          early_stopping_rounds=200,
          eval_metric='auc',
          verbose=200)
    pred_y = m.predict_proba(x_val)[:,1]
    print("err_lgm: ",roc_auc_score(y_val,pred_y))
    err.append(roc_auc_score(y_val, pred_y))
    pred_test = m.predict_proba(X_test)[:,1]
    i = i + 1
    y_pred_tot_lgm.append(pred_test)

Training until validation scores don't improve for 200 rounds
[200]	training's auc: 0.875909	training's binary_logloss: 0.357334	valid_1's auc: 0.784807	valid_1's binary_logloss: 0.429058
Early stopping, best iteration is:
[83]	training's auc: 0.832707	training's binary_logloss: 0.391202	valid_1's auc: 0.789069	valid_1's binary_logloss: 0.425621
err_lgm:  0.7890690867127561
Training until validation scores don't improve for 200 rounds
[200]	training's auc: 0.869527	training's binary_logloss: 0.363174	valid_1's auc: 0.795682	valid_1's binary_logloss: 0.418834
Early stopping, best iteration is:
[38]	training's auc: 0.80855	training's binary_logloss: 0.411039	valid_1's auc: 0.802593	valid_1's binary_logloss: 0.4177
err_lgm:  0.8025929253435629
Training until validation scores don't improve for 200 rounds
[200]	training's auc: 0.874735	training's binary_logloss: 0.359738	valid_1's auc: 0.790699	valid_1's binary_logloss: 0.424212
Early stopping, best iteration is:
[104]	training's auc: 0.841267	training's binary_logloss: 0.386592	valid_1's auc: 0.792948	valid_1's binary_logloss: 0.421655
err_lgm:  0.7929480018548184
Training until validation scores don't improve for 200 rounds
[200]	training's auc: 0.872295	training's binary_logloss: 0.360057	valid_1's auc: 0.774518	valid_1's binary_logloss: 0.429617
Early stopping, best iteration is:
[51]	training's auc: 0.81487	training's binary_logloss: 0.404373	valid_1's auc: 0.784119	valid_1's binary_logloss: 0.42434
err_lgm:  0.7841185134052778
Training until validation scores don't improve for 200 rounds
[200]	training's auc: 0.876143	training's binary_logloss: 0.356984	valid_1's auc: 0.760046	valid_1's binary_logloss: 0.448064
Early stopping, best iteration is:
[75]	training's auc: 0.829079	training's binary_logloss: 0.392611	valid_1's auc: 0.768598	valid_1's binary_logloss: 0.442589
err_lgm:  0.7685975834668239
Training until validation scores don't improve for 200 rounds
[200]	training's auc: 0.872038	training's binary_logloss: 0.361456	valid_1's auc: 0.7736	valid_1's binary_logloss: 0.432073
Early stopping, best iteration is:
[90]	training's auc: 0.83034	training's binary_logloss: 0.39291	valid_1's auc: 0.775761	valid_1's binary_logloss: 0.428337
err_lgm:  0.7757614021242313
Training until validation scores don't improve for 200 rounds
[200]	training's auc: 0.874047	training's binary_logloss: 0.358848	valid_1's auc: 0.769151	valid_1's binary_logloss: 0.44388
Early stopping, best iteration is:
[53]	training's auc: 0.819032	training's binary_logloss: 0.402078	valid_1's auc: 0.770753	valid_1's binary_logloss: 0.43982
err_lgm:  0.7707533458288119
Training until validation scores don't improve for 200 rounds
[200]	training's auc: 0.867394	training's binary_logloss: 0.364379	valid_1's auc: 0.77683	valid_1's binary_logloss: 0.427811
Early stopping, best iteration is:
[84]	training's auc: 0.827047	training's binary_logloss: 0.395286	valid_1's auc: 0.782244	valid_1's binary_logloss: 0.424615
err_lgm:  0.782243924895597
Training until validation scores don't improve for 200 rounds
[200]	training's auc: 0.870678	training's binary_logloss: 0.362101	valid_1's auc: 0.795828	valid_1's binary_logloss: 0.420461
Early stopping, best iteration is:
[122]	training's auc: 0.842791	training's binary_logloss: 0.383712	valid_1's auc: 0.798006	valid_1's binary_logloss: 0.419017
err_lgm:  0.7980059846765972
Training until validation scores don't improve for 200 rounds
[200]	training's auc: 0.869743	training's binary_logloss: 0.362764	valid_1's auc: 0.793859	valid_1's binary_logloss: 0.419026
Early stopping, best iteration is:
[64]	training's auc: 0.819604	training's binary_logloss: 0.400764	valid_1's auc: 0.802894	valid_1's binary_logloss: 0.414627
err_lgm:  0.8028943474400712

In [48]:
np.mean(err,0)

0.7866985115748548

In [49]:
from xgboost import XGBClassifier

errxgb = []
y_pred_tot_xgb = []

from sklearn.model_selection import KFold,StratifiedKFold

fold = StratifiedKFold(n_splits=10,shuffle=True,random_state=1994)
i = 1
for train_index, test_index in fold.split(X,y):
    x_train, x_val = X.iloc[train_index], X.iloc[test_index]
    y_train, y_val = y[train_index], y[test_index]
    m = XGBClassifier(boosting_type='gbdt',
                      max_depth=5,
                      learning_rate=0.07,
                      n_estimators=5000,
                      random_state=1994)
    m.fit(x_train, y_train,
          eval_set=[(x_train,y_train),(x_val, y_val)],
          early_stopping_rounds=200,
          eval_metric='auc',
          verbose=200)
    pred_y = m.predict_proba(x_val)[:,-1]
    print("err_xgb: ",roc_auc_score(y_val,pred_y))
    errxgb.append(roc_auc_score(y_val, pred_y))
    pred_test = m.predict_proba(X_test)[:,-1]
    i = i + 1
    y_pred_tot_xgb.append(pred_test)

[0]	validation_0-auc:0.75736	validation_1-auc:0.758177
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 200 rounds.
[200]	validation_0-auc:0.868186	validation_1-auc:0.787687
Stopping. Best iteration:
[128]	validation_0-auc:0.846731	validation_1-auc:0.790637

err_xgb:  0.7906373830199815
[0]	validation_0-auc:0.756207	validation_1-auc:0.767169
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 200 rounds.
[200]	validation_0-auc:0.862548	validation_1-auc:0.799925
Stopping. Best iteration:
[48]	validation_0-auc:0.811964	validation_1-auc:0.80523

err_xgb:  0.8052295864598263
[0]	validation_0-auc:0.757037	validation_1-auc:0.762093
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 200 rounds.
[200]	validation_0-auc:0.867394	validation_1-auc:0.792579
Stopping. Best iteration:
[89]	validation_0-auc:0.831035	validation_1-auc:0.794273

err_xgb:  0.7942725897900682
[0]	validation_0-auc:0.759083	validation_1-auc:0.749995
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 200 rounds.
[200]	validation_0-auc:0.864986	validation_1-auc:0.774721
Stopping. Best iteration:
[47]	validation_0-auc:0.812633	validation_1-auc:0.78368

err_xgb:  0.7836804970069977
[0]	validation_0-auc:0.761947	validation_1-auc:0.723023
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 200 rounds.
[200]	validation_0-auc:0.868001	validation_1-auc:0.761695
Stopping. Best iteration:
[104]	validation_0-auc:0.836229	validation_1-auc:0.76503

err_xgb:  0.7650302198381249
[0]	validation_0-auc:0.761623	validation_1-auc:0.733994
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 200 rounds.
[200]	validation_0-auc:0.866518	validation_1-auc:0.776082
[400]	validation_0-auc:0.908805	validation_1-auc:0.771833
Stopping. Best iteration:
[205]	validation_0-auc:0.868772	validation_1-auc:0.776463

err_xgb:  0.7764631218966822
[0]	validation_0-auc:0.763164	validation_1-auc:0.732146
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 200 rounds.
[200]	validation_0-auc:0.86638	validation_1-auc:0.770238
Stopping. Best iteration:
[134]	validation_0-auc:0.847152	validation_1-auc:0.773172

err_xgb:  0.773171549768176
[0]	validation_0-auc:0.762956	validation_1-auc:0.744331
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 200 rounds.
[200]	validation_0-auc:0.862431	validation_1-auc:0.77346
Stopping. Best iteration:
[53]	validation_0-auc:0.816492	validation_1-auc:0.780445

err_xgb:  0.7804452336325671
[0]	validation_0-auc:0.758236	validation_1-auc:0.750002
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 200 rounds.
[200]	validation_0-auc:0.859831	validation_1-auc:0.793179
Stopping. Best iteration:
[117]	validation_0-auc:0.837934	validation_1-auc:0.796521

err_xgb:  0.7965209956923481
[0]	validation_0-auc:0.756641	validation_1-auc:0.766648
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 200 rounds.
[200]	validation_0-auc:0.865984	validation_1-auc:0.793338
Stopping. Best iteration:
[43]	validation_0-auc:0.808811	validation_1-auc:0.801313

err_xgb:  0.8013126829107889

In [50]:
from catboost import CatBoostClassifier,Pool, cv
errCB = []
y_pred_tot_cb = []
from sklearn.model_selection import KFold,StratifiedKFold

fold = StratifiedKFold(n_splits=15,shuffle=True,random_state=1994)
i = 1
for train_index, test_index in fold.split(X,y):
    x_train, x_val = X.iloc[train_index], X.iloc[test_index]
    y_train, y_val = y[train_index], y[test_index]
    m = CatBoostClassifier(n_estimators=5000,
                           random_state=1994,
                           eval_metric='AUC',
                           learning_rate=0.03)
    m.fit(x_train, y_train,
          eval_set=[(x_train,y_train),(x_val, y_val)],
          early_stopping_rounds=200,
          verbose=200)
    pred_y = m.predict_proba(x_val)[:,-1]
    print("err_cb: ",roc_auc_score(y_val,pred_y))
    errCB.append(roc_auc_score(y_val,pred_y))
    pred_test = m.predict_proba(X_test)[:,-1]
    i = i + 1
    y_pred_tot_cb.append(pred_test)

0:	test: 0.7475678	test1: 0.7456551	best: 0.7456551 (0)	total: 98.6ms	remaining: 8m 12s
200:	test: 0.8049473	test1: 0.7877990	best: 0.7877990 (200)	total: 2.47s	remaining: 58.9s
400:	test: 0.8279002	test1: 0.7909136	best: 0.7910797 (397)	total: 4.82s	remaining: 55.3s
600:	test: 0.8500428	test1: 0.7900385	best: 0.7916433 (432)	total: 7.12s	remaining: 52.1s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.791643307
bestIteration = 432

Shrink model to first 433 iterations.
err_cb:  0.7916433069628234
0:	test: 0.7453636	test1: 0.7587499	best: 0.7587499 (0)	total: 19.1ms	remaining: 1m 35s
200:	test: 0.8046842	test1: 0.8028916	best: 0.8028916 (200)	total: 2.44s	remaining: 58.3s
400:	test: 0.8275186	test1: 0.8060685	best: 0.8066825 (364)	total: 5.04s	remaining: 57.8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8066825068
bestIteration = 364

Shrink model to first 365 iterations.
err_cb:  0.8066825067706063
0:	test: 0.7462057	test1: 0.7473800	best: 0.7473800 (0)	total: 21.2ms	remaining: 1m 45s
200:	test: 0.8050077	test1: 0.7987699	best: 0.7988144 (199)	total: 3.29s	remaining: 1m 18s
400:	test: 0.8270568	test1: 0.7993157	best: 0.7999772 (253)	total: 5.86s	remaining: 1m 7s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7999771594
bestIteration = 253

Shrink model to first 254 iterations.
err_cb:  0.7999771594006864
0:	test: 0.7459437	test1: 0.7728102	best: 0.7728102 (0)	total: 67.6ms	remaining: 5m 37s
200:	test: 0.8038994	test1: 0.8036391	best: 0.8036391 (200)	total: 2.17s	remaining: 51.7s
400:	test: 0.8269958	test1: 0.8067656	best: 0.8069940 (392)	total: 4.04s	remaining: 46.3s
600:	test: 0.8470835	test1: 0.8066261	best: 0.8070236 (412)	total: 5.85s	remaining: 42.8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8070236326
bestIteration = 412

Shrink model to first 413 iterations.
err_cb:  0.8070236326045106
0:	test: 0.7461706	test1: 0.7474037	best: 0.7474037 (0)	total: 11.4ms	remaining: 57s
200:	test: 0.8049268	test1: 0.7913022	best: 0.7913022 (200)	total: 1.85s	remaining: 44.2s
400:	test: 0.8273691	test1: 0.7926845	best: 0.7931235 (394)	total: 3.7s	remaining: 42.5s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7931234965
bestIteration = 394

Shrink model to first 395 iterations.
err_cb:  0.7931234964508082
0:	test: 0.7399670	test1: 0.7258139	best: 0.7258139 (0)	total: 52.3ms	remaining: 4m 21s
200:	test: 0.8055482	test1: 0.7782613	best: 0.7790840 (160)	total: 1.91s	remaining: 45.6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7790840485
bestIteration = 160

Shrink model to first 161 iterations.
err_cb:  0.7790840485350695
0:	test: 0.7497033	test1: 0.6985144	best: 0.6985144 (0)	total: 7.78ms	remaining: 38.9s
200:	test: 0.8074742	test1: 0.7558819	best: 0.7560906 (176)	total: 1.86s	remaining: 44.4s
400:	test: 0.8294749	test1: 0.7571042	best: 0.7573498 (384)	total: 3.71s	remaining: 42.5s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7573498076
bestIteration = 384

Shrink model to first 385 iterations.
err_cb:  0.7573498076353951
0:	test: 0.7491672	test1: 0.7292690	best: 0.7292690 (0)	total: 8.63ms	remaining: 43.1s
200:	test: 0.8052947	test1: 0.7715167	best: 0.7715167 (200)	total: 1.85s	remaining: 44.3s
400:	test: 0.8264237	test1: 0.7731385	best: 0.7732717 (354)	total: 3.71s	remaining: 42.6s
600:	test: 0.8473933	test1: 0.7737925	best: 0.7744140 (530)	total: 5.56s	remaining: 40.7s
800:	test: 0.8636978	test1: 0.7740115	best: 0.7745827 (662)	total: 7.37s	remaining: 38.6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7745827168
bestIteration = 662

Shrink model to first 663 iterations.
err_cb:  0.7745827167801124
0:	test: 0.7479853	test1: 0.7382347	best: 0.7382347 (0)	total: 8.4ms	remaining: 42s
200:	test: 0.8048223	test1: 0.7866765	best: 0.7866765 (200)	total: 1.82s	remaining: 43.5s
400:	test: 0.8270161	test1: 0.7888221	best: 0.7901569 (369)	total: 3.63s	remaining: 41.7s
600:	test: 0.8478549	test1: 0.7901243	best: 0.7905771 (548)	total: 5.47s	remaining: 40s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7905770938
bestIteration = 548

Shrink model to first 549 iterations.
err_cb:  0.7905770938147381
0:	test: 0.7486482	test1: 0.7231711	best: 0.7231711 (0)	total: 12ms	remaining: 1m
200:	test: 0.8066206	test1: 0.7663525	best: 0.7669281 (43)	total: 1.84s	remaining: 44.1s
400:	test: 0.8285535	test1: 0.7674504	best: 0.7680216 (312)	total: 3.81s	remaining: 43.7s
600:	test: 0.8486376	test1: 0.7698653	best: 0.7704632 (534)	total: 5.63s	remaining: 41.2s
800:	test: 0.8645057	test1: 0.7710136	best: 0.7711142 (792)	total: 7.59s	remaining: 39.8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.771114235
bestIteration = 792

Shrink model to first 793 iterations.
err_cb:  0.7711142349807636
0:	test: 0.7412953	test1: 0.7295857	best: 0.7295857 (0)	total: 9.9ms	remaining: 49.5s
200:	test: 0.8059140	test1: 0.7758582	best: 0.7759145 (198)	total: 1.83s	remaining: 43.8s
400:	test: 0.8276672	test1: 0.7781444	best: 0.7788503 (277)	total: 3.68s	remaining: 42.2s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7788502516
bestIteration = 277

Shrink model to first 278 iterations.
err_cb:  0.7788502515537142
0:	test: 0.7454020	test1: 0.7605741	best: 0.7605741 (0)	total: 12ms	remaining: 1m
200:	test: 0.8051812	test1: 0.7813229	best: 0.7813229 (200)	total: 1.86s	remaining: 44.5s
400:	test: 0.8285858	test1: 0.7846197	best: 0.7846197 (400)	total: 3.73s	remaining: 42.8s
600:	test: 0.8494353	test1: 0.7842409	best: 0.7849778 (461)	total: 5.57s	remaining: 40.8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7849778041
bestIteration = 461

Shrink model to first 462 iterations.
err_cb:  0.7849778040840485
0:	test: 0.7468045	test1: 0.7543696	best: 0.7543696 (0)	total: 8.88ms	remaining: 44.4s
200:	test: 0.8048284	test1: 0.7900059	best: 0.7900829 (197)	total: 1.89s	remaining: 45.2s
400:	test: 0.8263564	test1: 0.7910654	best: 0.7912637 (378)	total: 3.73s	remaining: 42.8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7912636875
bestIteration = 378

Shrink model to first 379 iterations.
err_cb:  0.7912636874815034
0:	test: 0.7447563	test1: 0.7847588	best: 0.7847588 (0)	total: 26ms	remaining: 2m 9s
200:	test: 0.8032867	test1: 0.8182687	best: 0.8182746 (192)	total: 1.9s	remaining: 45.5s
400:	test: 0.8270054	test1: 0.8219917	best: 0.8219917 (400)	total: 3.71s	remaining: 42.6s
600:	test: 0.8484498	test1: 0.8211986	best: 0.8224859 (428)	total: 5.52s	remaining: 40.4s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8224859426
bestIteration = 428

Shrink model to first 429 iterations.
err_cb:  0.822485942586564
0:	test: 0.7477639	test1: 0.7430912	best: 0.7430912 (0)	total: 9.46ms	remaining: 47.3s
200:	test: 0.8063380	test1: 0.7846893	best: 0.7848372 (197)	total: 1.85s	remaining: 44.3s
400:	test: 0.8279309	test1: 0.7842809	best: 0.7863022 (295)	total: 3.74s	remaining: 42.9s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7863021604
bestIteration = 295

Shrink model to first 296 iterations.
err_cb:  0.7863021604024859

In [51]:
np.mean(errCB)

0.7890025233362553

In [52]:
(np.mean(errxgb, 0) + np.mean(err, 0) + np.mean(errCB, 0))/3

0.787459140304222

In [53]:
submission = pd.DataFrame()
submission['ID'] = combine[combine['default_payment_next_month'].isnull()==True]['ID']
submission['default_payment_next_month'] = (np.mean(y_pred_tot_lgm, 0) + np.mean(y_pred_tot_cb, 0) + 
                                            np.mean(y_pred_tot_xgb, 0))/3
submission.to_csv('rfr_lrg.csv', index=False, header=True)
submission.shape

(9000, 2)